name: Backend CI - Build and Push to ACR

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/backend_ci.yml"
  workflow_dispatch:

jobs:
  test_and_lint_backends:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Echo tests placeholder
        run: echo "Run unit tests/lint here"

  build_and_push_images:
    runs-on: ubuntu-latest
    needs: test_and_lint_backends
    env:
      # Secrets
      ACR_NAME: ${{ secrets.ACR_NAME }}                 # e.g. sit722w08pspushpindersingh2027
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}         # e.g. sit722w08pspushpindersingh2027.azurecr.io
      # Correct build contexts
      PRODUCT_PATH: backend/product_service
      ORDER_PATH:   backend/order_service
      # Image repo names (keep kebab-case unless your k8s manifests expect underscores)
      PRODUCT_REPO: product-service
      ORDER_REPO:   order-service
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate ACR secrets
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${ACR_NAME:-}" ] || [ -z "${REGISTRY:-}" ]; then
            echo "❌ ACR_NAME or ACR_LOGIN_SERVER is empty. Check repository secrets."
            exit 1
          fi
          echo "✅ Secrets present. Proceeding…"

      - name: Login to Azure Container Registry
        run: az acr login --name "$ACR_NAME"

      - name: Build & Push product-service
        run: |
          docker build -t $REGISTRY/$PRODUCT_REPO:${{ github.sha }} "$PRODUCT_PATH"
          docker push  $REGISTRY/$PRODUCT_REPO:${{ github.sha }}

      - name: Build & Push order-service
        run: |
          docker build -t $REGISTRY/$ORDER_REPO:${{ github.sha }} "$ORDER_PATH"
          docker push  $REGISTRY/$ORDER_REPO:${{ github.sha }}

      - name: Logout from Azure
        if: always()
        run: az logout
